### ISSUE TITLE
Game immediately crashes after turning on the slider

### ISSUE THREAD

**Issue by guiege** [loki-47-6F-64/gamescope-mode-change#4]

**Comment by guiege** [comment]
The game goes to the steam logo and then just boots back to the menu. I tried reinstalling but nothing changed.

**Comment by loki-47-6F-64** [comment]
It's possible the script to modify the resolution of Gamescope is crashing.

In Desktop mode, in the terminal, run the following:
`/home/deck/homebrew/plugins/gamescope-mode-change/gamescope-mode-change.py --display=":0"`
If the output is *not* the following:
```
xwayland:  no atom named "GAMESCOPE_XWAYLAND_MODE_CONTROL" on server ":0"
```
Then the script is failing.

If that is the case, could you post the output here?

**Comment by guiege** [comment]
Yep I just reinstalled and it worked. I was cloning from the ethan021021 repository by accident. Thx for your help
