### ISSUE TITLE
Do a release

### ISSUE THREAD

**Issue by dragonfax** [loki-47-6F-64/gamescope-mode-change#6]
Do a release so we can give the zipfile url to the plugin loader as a manual install url. Allows one to skip desktop mode, using git, and all that fuss just to get this plugin.

**Comment by loki-47-6F-64** [comment]
No, this plugin will soon be obsolete anyway.

Valve added in its beta a settings for modifying resolution for non-steam games.
https://steamcommunity.com/app/1675200/eventcomments/3428948355360837698
